### PR TITLE
Set cleanStaleWebpackAssets to false for Clean Webpack Plugin.

### PR DESCRIPTION
**Pull request by smy315**
This MR has the same fix made on Theme Scaffold by @samikeijonen on https://github.com/10up/theme-scaffold/issues/165 / https://github.com/10up/theme-scaffold/pull/169.

### CODE REVIEW

**Comment by smy315** [comment]
@timwright12 fixed.

**Comment by timwright12** [comment]
@smy315 still seeing a conflict

**Comment by smy315** [comment]
Looking at the diff for this PR, not seeing any conflicts: (https://github.com/10up/plugin-scaffold/pull/116/files). Will take a look later but something seems odd here.

**Comment by smy315** [comment]
@timwright12 had to create a new PR because after I submitted this PR, the file I updated had changed filename and not sure why but Git was being weird. Please review https://github.com/10up/plugin-scaffold/pull/121 instead.

**Pull request closed without merging**
